model_params:
  name: "SVG_VAQVAE"  # always keep this "VectorGPT"
  vector_decoder_model: "cnn" # "mlp" or "raster_conv"
  quantized_dim: 512
  codebook_size: 4096  # will be ignored for FSQ
  image_loss: "pyramid"  # "pyramid" or "mse"
  single_code_representation: true
  vq_method: "fsq"  # "vqvae", "FSQ", "vqtorch"
  fsq_levels: [7,5,5,5,5]  # will determine codebook_size, see Table 1 of FSQ paper - [7,5,5,5,5] for 4096 (e.g. StrokeNUWA), [8,5,5,5] for 1024
  num_segments: 15
  pred_color: true

data_params:
  dataset: "mnist"
  data_path: "/raid/marco.cipriano/data/SVG/Grimoire/MNIST/mnist_png"
  train_batch_size: 16
  val_batch_size:  16
  patch_size: 34 # HAS TO BE 224 FOR CLIP RES50 TO WORK, otherwise take 128
  num_workers: 8
  num_tiles_per_row: 3
  random_colors: true
  use_palette: true  # use a color palette of 9 colors rather than random colors
  padding_frac: 0.1  # fraction of the image that is padded with white background

exp_params:
  lr: 0.00002  # 0.00002
  weight_decay: 1.e-4  # specify positive float to enable, start experimenting with 1.e-4/1.e-3
  scheduler_gamma: 0.98  # 0.95 is a good starting value
  train_log_interval: 0.025 # len(dataset) / train_batch_size / desired_logging_frequency
  manual_seed: 1265
  schedule_pyramid_method: "linear"  # "linear" or "exponential" or null to disable scheduling, default disabled


trainer_params:
  devices: -1  # always keep at -1 as this takes all available GPUs specified through CUDA_VISIBLE_DEVICES
  max_epochs: 250  # dsnt matter too much, got early stopping implemented
  # accumulate_grad_batches: 2

logging_params:
  entity: "aiis-chair"  # comment to use default wandb entity "mfeuer"
  project: "grimoire-2"  # your wandb project name
  save_dir: "/raid/marco.cipriano/results/svg/Grimoire/VSQ"
  name: "VSQ_MNIST_COLOR"  # name of the run in wandb
  version: 1
  author: "Marco"  # will be a tag in wandb
  # id: null  # id of wandb run to continue
  # allow_val_change: False  # allow changing values in this config w.r.t. the run that you're continuing (good for changing loss weightings mid-run)