stage1_params:
  name: "VSQ"  # always keep this "VectorGPT"
  vector_decoder_model: "cnn" # "mlp" or "raster_conv"
  quantized_dim: 512
  codebook_size: 4096  # will be ignored for FSQ
  image_loss: "pyramid"  # "pyramid" or "mse"
  single_code_representation: true
  vq_method: "fsq"  # "vqvae", "FSQ", "vqtorch"
  fsq_levels: [7,5,5,5,5]  # will determine codebook_size, see Table 1 of FSQ paper - [7,5,5,5,5] for 4096 (e.g. StrokeNUWA), [8,5,5,5] for 1024
  num_segments: 15
  pred_color: false
  # Update this path to the checkpoint of the model you used to encode
#  checkpoint_path: "/raid/marco.cipriano/results/svg/Grimoire/VSQ/VSQ_MNIST_BW_P128_T14_P20_TH0.2/checkpoints/last.ckpt"
  checkpoint_path: "/raid/marco.cipriano/results/svg/Grimoire/VSQ/VSQ_MNIST_BW_P128_T6_P0_TH0.2_singleGPU_lowBS/checkpoints/last.ckpt"


model_params:
  name: "VQ_SVG_Stage2"
  max_seq_len: 256  # 512
  dim: 512 # 512
  depth: 16  # 12
  heads: 8
  text_encoder_str: "bert-base-uncased"
  use_alibi_positional_bias : False

data_params:
  dataset: "mnist"
#  csv_path: "/raid/marco.cipriano/data/SVG/Grimoire/MNIST/mnist_tokenized/VSQ_MNIST_BW_P128_T14_P20_TH0.2/split.csv"  # root path for CausalSVGDataModule in dataset.py
#  vq_token_npy_path: "/raid/marco.cipriano/data/SVG/Grimoire/MNIST/mnist_tokenized/VSQ_MNIST_BW_P128_T14_P20_TH0.2/vsq_tokenized.npy"
  csv_path: "/raid/marco.cipriano/data/SVG/Grimoire/MNIST/mnist_tokenized/VSQ_MNIST_BW_P128_T6_P0_TH0.2/split.csv"  # root path for CausalSVGDataModule in dataset.py
  vq_token_npy_path: "/raid/marco.cipriano/data/SVG/Grimoire/MNIST/mnist_tokenized/VSQ_MNIST_BW_P128_T6_P0_TH0.2/vsq_tokenized.npy"
  train_batch_size: 256  #32
  val_batch_size:  32  # 32
  num_workers: 8
  patch_size: 128
  width: 128
#  num_tiles_per_row: 14
  num_tiles_per_row: 6
  min_context_length: 10  # all samples below this will be removed from the dataset
  shuffle_vq_order: False  # whether to shuffle the order of the VQ tokens, its not really "shuffling", but more cutting the sequence into two parts and switching their order
  use_pre_computed_text_tokens_only: False  # if True, the text tokens that were pre-computed will be used as input, if False, the text will be tokenized in the dataloader (according to the specified fractions).

exp_params:
  lr: 0.0006  # 0.00002
  weight_decay: 1.e-4  # specify positive float to enable, start experimenting with 1.e-4/1.e-3
  scheduler_gamma: 0.96  # 0.95 is a good starting value
  train_log_interval: 0.05  # decides how often full generations are made and logged
  val_log_interval: 0.3
  metric_log_interval: 0.4
  manual_seed: 1265
  post_process: False  # whether to log with svg fixing

trainer_params:
  devices: -1  # always keep at -1 as this takes all available GPUs specified through CUDA_VISIBLE_DEVICES
  max_epochs: 100  # dsnt matter too much, got early stopping implemented
#  accumulate_grad_batches: 2

logging_params:
  entity: "aiis-chair"  # comment to use default wandb entity "mfeuer"
  project: "grimoire-2"  # your wandb project name
  save_dir: "/raid/marco.cipriano/results/svg/Grimoire/ART"
  name: "ART_MNIST_BW_P128_T6_P0_TH0.2"  # name of the run in wandb
  version: 0
  author: "Marco"  # will be a tag in wandb
  id: null  # id of wandb run to continue
  allow_val_change: False  # allow changing values in this config w.r.t. the run that you're continuing (good for changing loss weightings mid-run)