model_params:
  name: "VectorGPT"
  image_encoder_model: "resnet18"
  latent_transformer_dim: 256 # 256
  latent_transformer_heads: 8 # 8
  latent_transformer_depth: 8 # 8
  latent_transformer_layer_dropout: 0.1
  vector_decoder_latent_dim: 256 # 256
  vector_decoder_paths: 5
  vector_decoder_radius: 3
  vector_decoder_render_size : 128 # 128
  vector_decoder_filled: True
  stop_predictor_dims: [768, 512] #[768, 512]
  stop_predictor_activation: "relu"
  stop_predictor_num_classes: 1
  context_length: 2
  reconstruction_loss_weight: 0.7

data_params:
  dataset: "mnistCSVG"
  data_path: "/home/mfeuerpfeil/master/thesis/datasets/mnist_png"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 128 # has to be equal to vector_decoder_render_size
  num_workers: 4

exp_params:
  # log_fid: False # True
  # clip_sim_model: "openai/clip-vit-large-patch14"
  #clip_prompt_suffix: ". minimal flat 2d vector icon. black and white. on a white background. trending on artstation" # for VectorFusion, replace "black and white" with "linear color"
  LR: 0.0002 # was 0.0005 originally
  weight_decay: 0.0
  scheduler_gamma: 0.95
  train_log_interval: 200 # ~ 8000 / batch_size / 4
  manual_seed: 1265

trainer_params:
  devices: 1
  max_epochs: 250

logging_params:
  project: "test"
  save_dir: "/scratch2/moritz_logs/VectorGPT_mnist"
  name: "VectorGPT_mnist"
  version: 0
  author: "Moritz Feuerpfeil"
