wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1709553373.652148
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 79
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 79
      - 103
      3:
      - 5
      - 7
      - 13
      - 14
      - 15
      - 23
      4: 3.10.12
      5: 0.15.8
      6: 4.31.0
      8:
      - 2
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: lr-Adam-momentum
      5: 1
      6:
      - 1
    - 1: loss
      5: 1
      6:
      - 1
    - 1: Reconstruction_Loss
      5: 1
      6:
      - 1
    - 1: VQ_Loss
      5: 1
      6:
      - 1
    - 1: inner_distance_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train/mean_stroke_width
      5: 1
      6:
      - 1
    - 1: train/codebook_histogram._type
      5: 1
      6:
      - 1
    - 1: train/codebook_histogram.sha256
      5: 1
      6:
      - 1
    - 1: train/codebook_histogram.size
      5: 1
      6:
      - 1
    - 1: train/codebook_histogram.path
      5: 1
      6:
      - 1
    - 1: train/codebook_histogram.format
      5: 1
      6:
      - 1
    - 1: train/codebook_histogram.width
      5: 1
      6:
      - 1
    - 1: train/codebook_histogram.height
      5: 1
      6:
      - 1
    - 1: train/codebook_histogram.caption
      5: 1
      6:
      - 1
    - 1: train/side_by_side_recons._type
      5: 1
      6:
      - 1
    - 1: train/side_by_side_recons.sha256
      5: 1
      6:
      - 1
    - 1: train/side_by_side_recons.size
      5: 1
      6:
      - 1
    - 1: train/side_by_side_recons.path
      5: 1
      6:
      - 1
    - 1: train/side_by_side_recons.format
      5: 1
      6:
      - 1
    - 1: train/side_by_side_recons.width
      5: 1
      6:
      - 1
    - 1: train/side_by_side_recons.height
      5: 1
      6:
      - 1
    - 1: train/side_by_side_recons.caption
      5: 1
      6:
      - 1
    - 1: train/reconstruction._type
      5: 1
      6:
      - 1
    - 1: train/reconstruction.sha256
      5: 1
      6:
      - 1
    - 1: train/reconstruction.size
      5: 1
      6:
      - 1
    - 1: train/reconstruction.path
      5: 1
      6:
      - 1
    - 1: train/reconstruction.format
      5: 1
      6:
      - 1
    - 1: train/reconstruction.width
      5: 1
      6:
      - 1
    - 1: train/reconstruction.height
      5: 1
      6:
      - 1
    - 1: train/reconstruction.caption
      5: 1
      6:
      - 1
    - 1: val/mean_stroke_width
      5: 1
      6:
      - 1
    - 1: val/side_by_side_recons._type
      5: 1
      6:
      - 1
    - 1: val/side_by_side_recons.sha256
      5: 1
      6:
      - 1
    - 1: val/side_by_side_recons.size
      5: 1
      6:
      - 1
    - 1: val/side_by_side_recons.path
      5: 1
      6:
      - 1
    - 1: val/side_by_side_recons.format
      5: 1
      6:
      - 1
    - 1: val/side_by_side_recons.width
      5: 1
      6:
      - 1
    - 1: val/side_by_side_recons.height
      5: 1
      6:
      - 1
    - 1: val/side_by_side_recons.caption
      5: 1
      6:
      - 1
    - 1: val/reconstruction._type
      5: 1
      6:
      - 1
    - 1: val/reconstruction.sha256
      5: 1
      6:
      - 1
    - 1: val/reconstruction.size
      5: 1
      6:
      - 1
    - 1: val/reconstruction.path
      5: 1
      6:
      - 1
    - 1: val/reconstruction.format
      5: 1
      6:
      - 1
    - 1: val/reconstruction.width
      5: 1
      6:
      - 1
    - 1: val/reconstruction.height
      5: 1
      6:
      - 1
    - 1: val/reconstruction.caption
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
exp_params:
  desc: null
  value:
    lr: 2.0e-05
    manual_seed: 42
    scheduler_gamma: 0.98
    train_log_interval: 0.01
    val_log_interval: 0.1
    weight_decay: 0.0001
    continue_checkpoint: /scratch/mcipriano/results/svg/SVG_VQVAE/Stage1/VSQ_4/checkpoints/last.ckpt
data_params:
  desc: null
  value:
    channels: 3
    csv_path: datasets/figr8_final_paper_split.csv
    dataset: stage1
    individual_max_length: 3
    max_shapes_per_svg: 32
    num_workers: 8
    stroke_width: 0.4
    train_batch_size: 8
    val_batch_size: 4
    width: 128
model_params:
  desc: null
  value:
    fsq_levels:
    - 7
    - 5
    - 5
    - 5
    - 5
    geometric_constraint: inner_distance
    geometric_constraint_weight: 0.2
    name: SVG_VAQVAE
    num_codes_per_shape: 1
    num_segments: 2
    quantized_dim: 512
logging_params:
  desc: null
  value:
    author: Marco
    entity: aiis-chair
    name: Figr8 VSQ_4
    project: thesis
    save_dir: /scratch/mcipriano/results/svg/SVG_VQVAE/Stage1/VSQ_4
    version: 0
    id: 7ihdszrf
    allow_val_change: true
trainer_params:
  desc: null
  value:
    accumulate_grad_batches: 2
    devices: -1
    max_epochs: 250
    val_check_interval: 0.1
