model_params:
  name: "VectorVAEnLayers"
  in_channels: 3
  latent_dim: 128
  loss_fn: 'MSE'
  paths: 10
  T: 10
  beta: 0.1
  radius: 3
  scale_factor: 1
  learn_sampling: False
  only_auxillary_training: False
  memory_leak_training: False
  other_losses_weight: 0
  composite_fn: 'soft'
  optimize_colors: False
  imsize: 128

data_params:
  dataset: "raster_figr8"
  csv_path: "/scratch2/moritz_data/raster_figr8/split_only_star.csv"
  img_size: 128
  train_batch_size: 64
  val_batch_size:  64
  num_workers: 16
  invert: True
  channels: 3

exp_params:
  LR: 0.0001
  weight_decay: 1.e-4
  scheduler_gamma: 0.99
  grow: True
  manual_seed: 12345
  train_log_interval: 20
  kld_weight: 0.1
  resample_circle_segments: True
  continue_checkpoint: "/scratch2/moritz_logs/Im2Vec/figr8_star/checkpoints/last.ckpt"

trainer_params:
  devices: -1
  max_epochs: 350
  accumulate_grad_batches: 2

logging_params:
  entity: "aiis-chair-students"  # comment to use default wandb entity "mfeuer"
  project: "generative-svg"  # your wandb project name
  save_dir: "/scratch2/moritz_logs/Im2Vec/figr8_star"
  name: "Im2Vec Figr8 - Star only"  # name of the run in wandb
  version: 0
  author: "Moritz"  # will be a tag in wandb
  id: null  # id of wandb run to continue
  allow_val_change: False  # allow changing values in this config w.r.t. the run that you're continuing (good for changing loss weightings mid-run)
  