stage1_params:
  name: "SVG_VAQVAE"  # always keep this "VectorGPT"
  vector_decoder_model: "mlp" # "mlp" or "raster_conv"
  quantized_dim: 512
  codebook_size: 4096  # will be ignored for FSQ
  image_loss: "mse"  # "pyramid" or "mse"
  single_code_representation: true
  vq_method: "fsq"  # "vqvae", "FSQ", "vqtorch"
  fsq_levels: [7,5,5,5,5]  # will determine codebook_size, see Table 1 of FSQ paper - [7,5,5,5,5] for 4096 (e.g. StrokeNUWA), [8,5,5,5] for 1024
  checkpoint_path: "/scratch2/gesùbambino/stage_1_fonts.pth"

model_params:
  name: "VQ_SVG_Stage2"
  max_seq_len: 256  # 512
  dim: 512 # 512
  depth: 12  # 12
  heads: 8
  text_encoder_str: "bert-base-uncased"
  use_alibi_positional_bias : False

data_params:
  dataset: "tokens"  # must be in the DATASETMAP in run.py
  csv_path: "/scratch2/moritz_data/full_fonts/merged_csv/combined_full_fonts_fixed.csv"  # root path for CausalSVGDataModule in dataset.py
  vq_token_npy_path: "/scratch2/moritz_data/full_fonts/merged_csv/combined_vq_tokens_fixed.npy"
  train_batch_size: 64  # 64
  val_batch_size:  64  # 64
  num_workers: 16
  width: 128
  min_context_length: 10  # all samples below this will be removed from the dataset
  fraction_of_class_only_inputs: 0.2  # fraction of samples that will only have the "class" entry of the dataframe as input
  fraction_of_blank_inputs: 0.1  # fraction of samples that will have empty text input
  shuffle_vq_order: True  # whether to shuffle the order of the VQ tokens, its not really "shuffling", but more cutting the sequence into two parts and switching their order
  use_pre_computed_text_tokens_only: False  # if True, the text tokens that were pre-computed will be used as input, if False, the text will be tokenized in the dataloader (according to the specified fractions).

exp_params:
  lr: 0.0006  # 0.00002
  weight_decay: 1.e-4  # specify positive float to enable, start experimenting with 1.e-4/1.e-3
  scheduler_gamma: 0.96  # 0.95 is a good starting value
  train_log_interval: 0.05  # 0.05 means every 5% of an epoch
  val_log_interval: 0.05
  metric_log_interval: 0.1
  manual_seed: 1265
  # continue_checkpoint: "/scratch2/moritz_logs/SVG_VQVAE/Stage2/all_fonts_full_single_code/checkpoints/last.ckpt"  # path to a checkpoint to continue training from

trainer_params:
  devices: -1  # always keep at -1 as this takes all available GPUs specified through CUDA_VISIBLE_DEVICES
  max_epochs: 400  # dsnt matter too much, got early stopping implemented
  accumulate_grad_batches: 2

logging_params:
  entity: "aiis-chair-students"  # comment to use default wandb entity "mfeuer"
  project: "generative-svg"  # your wandb project name
  save_dir: "/scratch2/moritz_logs/SVG_VQVAE/Stage2/filtered_fonts_full_single_code"
  name: "Stage 2 filtered Fonts, single code representation, text enc. frozen"  # name of the run in wandb
  version: 2
  author: "Moritz"  # will be a tag in wandb