model_params:
  name: "VQ_Transformer"
  num_tokens: 17387
  max_seq_len: 256
  dim: 512
  depth: 12
  heads: 8

data_params:
  dataset: "tokens"  # must be in the DATASETMAP in run.py
  csv_path: "/scratch2/moritz_data/glyphazzn/B_simplified/tokenized/split.csv"  # root path for CausalSVGDataModule in dataset.py
  train_batch_size: 8
  val_batch_size:  8
  num_workers: 8

exp_params:
  lr: 0.00002  # 0.00002
  checkpoint_path: "/scratch2/moritz_logs/SVG_VQVAE/Stage1/glyphazzn_B_simplified_single_code/checkpoints/last-v3.ckpt"
  weight_decay: 1.e-4  # specify positive float to enable, start experimenting with 1.e-4/1.e-3
  scheduler_gamma: 0.98  # 0.95 is a good starting value
  train_log_interval: 100 # len(dataset) / train_batch_size / desired_logging_frequency
  manual_seed: 1265

trainer_params:
  devices: -1  # always keep at -1 as this takes all available GPUs specified through CUDA_VISIBLE_DEVICES
  max_epochs: 250  # dsnt matter too much, got early stopping implemented
  accumulate_grad_batches: 2

logging_params:
  # entity: "aiis-chair"  # comment to use default wandb entity "mfeuer"
  project: "thesis"  # your wandb project name
  save_dir: "/scratch2/moritz_logs/VQ_Transformer/glyphazzn_B_simplified_single_code"
  name: "VQ_Transformer glyphazzn_B, single code representation"  # name of the run in wandb
  version: 0
  author: "Moritz"  # will be a tag in wandb