model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

data_params:
  dataset: "nounproject"
  data_path: "/scratch1/nounproject/v1"
  train_batch_size: 128
  val_batch_size:  128
  patch_size: 64
  num_workers: 4

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  devices: 1
  max_epochs: 2000

logging_params:
  project: "thesis"
  save_dir: "/scratch2/moritz_logs/"
  name: "VanillaVAE_NounProjectV1"
  
