model_params:
  name: "VectorGPT"
  image_encoder_model: "resnet18"
  latent_transformer_dim: 256
  latent_transformer_heads: 8
  latent_transformer_depth: 8
  latent_transformer_layer_dropout: 0.1
  vector_decoder_latent_dim: 256
  vector_decoder_paths: 5
  vector_decoder_radius: 3
  vector_decoder_render_size : 128
  stop_predictor_dims: [768, 512]
  stop_predictor_activation: "relu"
  stop_predictor_num_classes: 1
  context_length: 15

data_params:
  dataset: "causalSVG"
  root_path: "/scratch2/mcipriano/SVG/incremental_FIGR-8/length"
  channels: 3
  width: 128  # KEEP THIS SYNC WITH make_causal_svg_dateset
  context_length: 15  # KEEP THIS SYNC WITH make_causal_svg_dateset
  train_batch_size: 32
  val_batch_size:  32
  patch_size: 128 # HAS TO BE 224 FOR CLIP RES50 TO WORK, otherwise take 128
  num_workers: 4

exp_params:
  # log_fid: False # True
  # clip_sim_model: "openai/clip-vit-large-patch14"
  #clip_prompt_suffix: ". minimal flat 2d vector icon. black and white. on a white background. trending on artstation" # for VectorFusion, replace "black and white" with "linear color"
  LR: 0.0005 # was 0.0005 originally
  weight_decay: 0.0
  scheduler_gamma: 0.95
  train_log_interval: 200 # ~ 8000 / batch_size / 4
  manual_seed: 1265

trainer_params:
  devices: 1
  max_epochs: 250

logging_params:
  project: "test"
  save_dir: "/scratch2/mcipriano/SVG/results"
  name: "VectorGPT_FIGR8"
  version: 0