model_params:
  name: 'VQVAE'
  in_channels: 3
  embedding_dim: 32
  num_embeddings: 256
  img_size: 64
  beta: 0.25

data_params:
  dataset: "nounproject"
  data_path: "/scratch1/nounproject/v2"
  train_batch_size: 32
  val_batch_size:  32
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025 #0.00025
  manual_seed: 1265

trainer_params:
  devices: 1
  max_epochs: 500

logging_params:
  project: "test"
  save_dir: "/scratch2/moritz_logs/VQVAE_NounProject_hourglass"
  name: 'VQVAE_NounProject_hourglass'
