import numpy as np
import torch
from torch import Tensor
from torch import nn
from torch.nn import functional as F
from typing import List
import pydiffvg
import wandb

class MLPVectorHead(nn.Module):
    """
    The MLP vector head is the simplest possible head for VectorGPT. It takes the latent vector generated by the transformer and predicts the coordinates of cubic Bezier curves directly through a linear layer.
    
    Constructor Args:
        - latent_dim: int, the dimensionality of the latent vector input
        - segments: int, the number of segments that make a single path, default 4
        - render_size: int, the size of the rasterized image, default 128
        - max_stroke_width: float, the width of the stroke of the cubic Bezier curves, default 1.0
    """
    def __init__(
        self,
        latent_dim: int,
        segments: int = 4,
        render_size: int = 128,
        max_stroke_width: float = 1.0,
        filled: bool = False,
        **kwargs
    ) -> None:
        super(MLPVectorHead, self).__init__()

        self.latent_dim = latent_dim
        self.segments = segments
        self.render_size = render_size
        self.max_stroke_width = max_stroke_width
        self.filled = filled

        self.point_predictor = nn.Sequential(
            # nn.Linear(latent_dim, 256),
            # nn.SELU(),
            # nn.Linear(256, 256),
            # nn.SELU(),
            nn.Linear(
                self.latent_dim, 2 + (self.segments * 3 * 2)
            ),  # 2 for start coordinates, then 3 points per path (they're connected) with 2 coordinates per point
            nn.Sigmoid(),
        )

        self.stop_predictor = nn.Sequential(
            nn.Linear(self.latent_dim, 1),
            nn.Sigmoid(),
        )

        self.stroke_predictor = nn.Sequential(
            nn.Linear(self.latent_dim, 1),
            nn.Sigmoid(),
        )

        self.alpha_predictor = nn.Sequential(
            nn.Linear(self.latent_dim, 1),
            nn.Sigmoid(),
        )

    def raster(
        self,
        all_points: Tensor,
        stroke_widths: Tensor,
        alphas: Tensor,
        color: Tensor = Tensor([0.0, 0.0, 0.0, 1.0]),
        verbose: bool = False,
        white_background: bool = True,
        **kwargs
    ) -> Tensor:
        """
        Rasterizes the predicted points of the cubic Bezier curves.

        Args:
            all_points: Tensor of shape (batch_size, 2 + self.segments * 3, 2)
            stroke_widths: Tensor of shape (batch_size, 1)
            alphas: Tensor of shape (batch_size, 1)
            color: Tensor of shape (4)
            verbose: bool, currently unused
            white_background: bool, if True, the output will have a white background

        Returns:
            output: Tensor of shape (batch_size, 4, self.render_size, self.render_size)
        """
        device = all_points.device
        if verbose:
            render_size = 768
        else:
            render_size = self.render_size

        all_points = all_points * render_size
        #stroke_widths = stroke_widths * self.max_stroke_width  # scale the stroke width because of Sigmoid activation
        num_ctrl_pts = torch.zeros(self.segments, dtype=torch.int32).to(device) + 2
        outputs = []

        if self.filled:
            fill_color = color
        else:
            fill_color = None

        for batch_idx in range(all_points.shape[0]):
            render = pydiffvg.RenderFunction.apply
            shapes = []
            shape_groups = []
            points = all_points[batch_idx].contiguous()  # is a prediction of the model
            alpha = alphas[batch_idx]  # is a prediction of the model
            color[-1] = alpha  # is a prediction of the model
            stroke_width = stroke_widths[batch_idx]  # is a prediction of the model

            path = pydiffvg.Path(
                num_control_points=num_ctrl_pts,
                points=points,
                is_closed=False,
                # stroke_width=torch.tensor([5.]),  # this is fine
                # stroke_width=torch.tensor([5.], requires_grad=True),  # this also breaks the backpropagation
                stroke_width=stroke_width,  # this breaks the backpropagation
            )

            shapes.append(path)
            path_group = pydiffvg.ShapeGroup(
                shape_ids=torch.tensor([len(shapes) - 1]),
                fill_color=fill_color,
                stroke_color=color,
            )
            shape_groups.append(path_group)
            scene_args = pydiffvg.RenderFunction.serialize_scene(
                render_size, render_size, shapes, shape_groups
            )
            out = render(
                render_size,  # width
                render_size,  # height
                3,  # num_samples_x
                3,  # num_samples_y
                102,  # seed
                None,
                *scene_args
            )
            out = out.permute(2, 0, 1).view(4, render_size, render_size)
            outputs.append(out)
        output = torch.stack(outputs).to(all_points.device)
        if white_background:
            alpha = output[:, 3:4, :, :]
            output_white_bg = output[:, :3, :, :] * alpha + (1 - alpha)
            output = torch.cat([output_white_bg, alpha], dim=1)
        del num_ctrl_pts
        return output

    def forward(self, z: Tensor, verbose: bool = False) -> Tensor:
        point_predictions = self.point_predictor(z)
        stroke_widths = self.stroke_predictor(z)
        alphas = self.alpha_predictor(z)
        stop_predictions = self.stop_predictor(z)

        batch_size = point_predictions.shape[0]
        point_predictions = point_predictions.view(batch_size, 1 + self.segments * 3, 2)

        raster_images = self.raster(point_predictions, stroke_widths, alphas, verbose=verbose)

        return raster_images, stop_predictions
    
class CNNVectorHead(nn.Module):
    """
    The CNNVectorHead is similar to Im2Vec. It uses a unit cirlce as a filled shape as a basis and iteratively deforms that shape using a CNN.
    """

    def __init__(self,
                 latent_dim:int = 128,
                 segments: int = 4,
                 imsize:int=64,
                 filled:bool = True,
                 pred_color: bool = False,
                 pred_alpha: bool = False,
                 pred_stroke_width: bool = False,
                 max_stroke_width: float = 10.0,
                 radius:float = 3.):
        super(CNNVectorHead, self).__init__()

        self.latent_dim = latent_dim
        self.segments = segments
        self.imsize = imsize
        self.filled = filled
        self.pred_color = pred_color
        self.pred_alpha = pred_alpha
        self.pred_stroke_width = pred_stroke_width
        self.max_stroke_width = max_stroke_width
        self.radius = radius

        fused_latent_dim = latent_dim + 2 + 2 # 2 for point type (e.g. control point) and 2 for initial x-y-position on the circle
        self.num_points = self.segments * 3
        self.angles = torch.arange(0, self.num_points, dtype=torch.float32) * 6.28319 / self.num_points
        self.circle_point_positions = self.sample_circle(self.radius, self.angles)
        self.point_types = torch.tensor([[1,0],[0,1],[0,1]], dtype=torch.float32)

        self.point_predictor = nn.Sequential(
            nn.Conv1d(fused_latent_dim, fused_latent_dim*2, kernel_size=3, padding=2, padding_mode='circular', stride=1, dilation=1),
            nn.ReLU(),
            nn.Conv1d(fused_latent_dim*2, fused_latent_dim*2, kernel_size=3, padding=2, padding_mode='circular', stride=1, dilation=1),
            nn.ReLU(),
            nn.Conv1d(fused_latent_dim*2, fused_latent_dim*2, kernel_size=3, padding=2, padding_mode='circular', stride=1, dilation=1),
            nn.ReLU(),
            nn.Conv1d(fused_latent_dim*2, fused_latent_dim*2, kernel_size=3, padding=2, padding_mode='circular', stride=1, dilation=1),
            nn.ReLU(),
            nn.Conv1d(fused_latent_dim*2, 2, kernel_size=3, padding=2, padding_mode='circular', stride=1, dilation=1),
            nn.Sigmoid()
        )

        # TODO do color and alpha and all that

    def sample_circle(self, r, angles):
        """
        samples position on a circle of radius r, distances of positions are given by the angles, which are in [0, 2*pi]
        """
        pos = [(torch.cos(angles) * r), (torch.sin(angles) * r)]
        return torch.stack(pos, dim=-1)
    
    def raster(self, all_points, white_background=True):

        render_size = self.imsize
        bs = all_points.shape[0]

        outputs = []
        scenes = []
        all_points = all_points*render_size
        num_ctrl_pts = torch.zeros(self.segments, dtype=torch.int32).to(all_points.device) + 2
        color = torch.tensor([0,0,0,1]).to(all_points.device)
        for k in range(bs):
            # Get point parameters from network
            render = pydiffvg.RenderFunction.apply
            shapes = []
            shape_groups = []
            points = all_points[k].contiguous()#[self.sort_idx[k]] # .cpu()

            path = pydiffvg.Path(
                num_control_points=num_ctrl_pts, points=points,
                is_closed=True)

            shapes.append(path)
            path_group = pydiffvg.ShapeGroup(
                shape_ids=torch.tensor([len(shapes) - 1]),
                fill_color=color,
                stroke_color=color)
            shape_groups.append(path_group)
            scene_args = pydiffvg.RenderFunction.serialize_scene(render_size, render_size, shapes, shape_groups)
            scenes.append(scene_args)
            out = render(render_size,  # width
                         render_size,  # height
                         3,  # num_samples_x
                         3,  # num_samples_y
                         102,  # seed
                         None,
                         *scene_args)
            out = out.permute(2, 0, 1).view(4, render_size, render_size)#[:3]#.mean(0, keepdim=True)
            outputs.append(out)
        output =  torch.stack(outputs).to(all_points.device)

        # map to [-1, 1]
        if white_background:
            alpha = output[:, 3:4, :, :]
            output_white_bg = output[:, :3, :, :]*alpha + (1-alpha)
            output = torch.cat([output_white_bg, alpha], dim=1)
        del num_ctrl_pts, color
        return output, scenes

    
    def forward(self, z, **kwargs):
        logging_dict = {}
        bs = z.shape[0]
        z = z.repeat(1, self.segments*3, 1)
        print("z.shape: ", z.shape)
        batched_point_types = self.point_types[None, :, :].repeat(bs, self.segments, 1)
        print("batched_point_types.shape: ",batched_point_types.shape)
        feats = torch.cat([z, batched_point_types], dim=-1)
        positions = self.circle_point_positions[None, :, :].repeat(bs, 1, 1)
        feats = torch.cat([feats, positions], dim=-1)

        all_points = self.point_predictor(feats)

        all_points = all_points.view(bs, 1, self.segments * 3, 2)
        all_widths = torch.ones(bs, self.segments, 1)
        all_alphas = torch.ones(bs, self.segments, 1)
        

        output, scenes = self.raster(
            all_points
        )

        # map to [-1, 1]
        # output = output*2.0 - 1.0

        return [output, scenes, all_points, all_widths], logging_dict


class MLPVectorHeadFixed(nn.Module):
    """
    For some f reason, I could not get the gradients to flow through the stroke width prediction in MLPVectorHead.
    So I started remixing: 
        - https://github.com/BachiLi/diffvg/blob/master/apps/generative_models/models.py#L17
        - https://github.com/BachiLi/diffvg/blob/master/apps/generative_models/rendering.py
        - https://github.com/BachiLi/diffvg/blob/master/apps/painterly_rendering.py

    This is the result. It is a bit messier than the original MLPVectorHead, but it works. God knows why.
    """
    def __init__(self, latent_dim=128, 
                 segments: int = 4, 
                 imsize=32,
                 color_output=False,
                 alpha_prediction = False,
                 stroke_width_predictor: bool = True,
                 max_stroke_width: float = 10.0):
        super(MLPVectorHeadFixed, self).__init__()

        self.stroke_width = max_stroke_width
        self.min_stroke_width = 0.3
        self.imsize = imsize
        self.segments = segments
        self.latent_dim = latent_dim
        self.stroke_width_predictor = stroke_width_predictor

        # 4 points bezier with n_segments -> 3*n_segments + 1 points
        self.point_predictor = nn.Sequential(
            nn.Linear(self.latent_dim, self.latent_dim),
            nn.SELU(),
            nn.Linear(self.latent_dim, self.latent_dim),
            nn.SELU(),
            nn.Linear(self.latent_dim, 2 * (self.segments * 3 + 1)),
            nn.Sigmoid()  # bound spatial extent
        )

        self.stroke_predictor = nn.Sequential(
            nn.Linear(self.latent_dim, self.latent_dim),
            nn.SELU(),
            nn.Linear(self.latent_dim, 1, bias=False),
            nn.Sigmoid()
        )

        self.alpha_predictor = None
        if alpha_prediction:
            self.alpha_predictor = nn.Sequential(
                nn.Linear(self.latent_dim, 1, bias=False),
                nn.Sigmoid()
            )

        self.color_predictor = None
        if color_output:
            self.color_predictor = nn.Sequential(
                nn.Linear(self.latent_dim, 3, bias=False),
                nn.Sigmoid()
            )

    def forward(self, z, primitive: str = "cubic", **kwargs):
        logging_dict = {}
        bs = z.shape[0]

        feats = z
        all_points = self.point_predictor(feats)

        all_width = self.stroke_predictor(feats)
        if self.stroke_width_predictor:
            all_widths = self.stroke_predictor(feats) * self.stroke_width
        else:
            # we block the stroke width to 4.7 which globally means 0.7
            # a more proper way to compute this would be checking the longest stroke in the dataset before-hand
            all_widths = torch.ones_like(all_width) * 4.7

        all_widths = torch.max(all_widths, torch.ones_like(all_widths)*self.min_stroke_width)  # enforce min stroke width

        # logging_dict["stroke_width"] = wandb.Histogram(all_widths.detach().cpu().flatten())
        logging_dict["mean_stroke_width"] = all_widths.detach().mean()

        if self.color_predictor:
            all_colors = self.color_predictor(feats)
            all_colors = all_colors.view(bs, 1, 3)
        else:
            all_colors = None
        
        if self.alpha_predictor:
            all_alphas = self.alpha_predictor(feats)
        else:
            all_alphas = torch.ones(all_widths.shape, device=all_widths.device)

        # min_width = self.stroke_width[0]
        # max_width = self.stroke_width[1]
        # all_widths = (max_width - min_width) * all_widths + min_width

        all_points = all_points.view(bs, 1, self.segments * 3 + 1, 2)

        output, scenes = self.bezier_render(
            all_points, all_widths, all_alphas,
            colors=all_colors,
            canvas_size=self.imsize,
            primitive=primitive
        )

        # map to [-1, 1]
        # output = output*2.0 - 1.0

        return [output, scenes, all_points, all_widths], logging_dict
    def render(self,
                canvas_width, 
                canvas_height, 
                shapes, 
                shape_groups, 
                samples=2,
                seed=42):
        
        _render = pydiffvg.RenderFunction.apply
        scene_args = pydiffvg.RenderFunction.serialize_scene(
            canvas_width, canvas_height, shapes, shape_groups)
        img = _render(canvas_width, canvas_height, samples, samples,
                    seed,   # seed
                    None,  # background image
                    *scene_args)
        return img

    def bezier_render(self, all_points: Tensor, all_widths: Tensor, all_alphas: Tensor,
                    canvas_size=32, primitive: str = "cubic", colors=None, white_background=True):
        device = all_points.device

        # all_points = 0.5*(all_points + 1.0) * canvas_size
        all_points = all_points * canvas_size

        eps = 1e-4
        all_points = all_points + eps*torch.randn_like(all_points, device=device)

        bs, num_strokes, num_pts, _ = all_points.shape
        num_segments = (num_pts - 1) // 3
        n_out = 4
        output = torch.zeros(bs, n_out, canvas_size, canvas_size,
                        device=device)

        scenes = []
        for batch in range(bs):
            shapes = []
            shape_groups = []
            for p in range(num_strokes):
                points = all_points[batch, p].contiguous()  # (num_pts, 2)
                if primitive == "cubic":
                    num_ctrl_pts = torch.zeros(num_segments, dtype=torch.int32) + 2
                elif primitive == "linear":
                    if num_segments > 1:
                        raise NotImplementedError("Linear primitive only supports 1 segment atm")
                    num_ctrl_pts = torch.zeros(num_segments, dtype=torch.int32)
                    points = points[[0, 3]]
                elif primitive == "quadratic":
                    num_ctrl_pts = torch.zeros(num_segments, dtype=torch.int32) + 1
                    points = points[[0, 1, 3]]
                else:
                    raise NotImplementedError(f"Primitive {primitive} not implemented")
                width = all_widths[batch, p]
                alpha = all_alphas[batch, p]
                if colors is not None:
                    color = colors[batch, p]
                else:
                    color = torch.zeros(3, device=device)

                color = torch.cat([color, alpha.view(1,)])

                path = pydiffvg.Path(
                    num_control_points=num_ctrl_pts, points=points,
                    stroke_width=width, is_closed=False)
                shapes.append(path)
                path_group = pydiffvg.ShapeGroup(
                    shape_ids=torch.tensor([len(shapes) - 1]),
                    fill_color=None,
                    stroke_color=color)
                shape_groups.append(path_group)

            # Rasterize
            scenes.append((canvas_size, canvas_size, shapes, shape_groups))
            raster = self.render(canvas_size, canvas_size, shapes, shape_groups,
                            samples=2)
            raster = raster.permute(2, 0, 1).view(4, canvas_size, canvas_size)

            # alpha = raster[3:4]
            # if colors is not None:  # color output
            #     image = raster[:3]
            #     alpha = alpha.repeat(3, 1, 1)
            # else:
            #     image = raster[:1]

            # # alpha compositing
            # image = image*alpha
            # output[k] = image
            output[batch] = raster

        output = output.to(device)
        
        if white_background:
            alpha = output[:, 3:4, :, :]
            output_white_bg = output[:, :3, :, :] * alpha + (1 - alpha)
            output = torch.cat([output_white_bg, alpha], dim=1)

        return output, scenes

class MLPRasterHead(nn.Module):
    """
    The MLPRasterHead is the simplest possible head for VectorGPT. It takes the latent vector generated by the transformer and predicts the raster image directly through a linear layer without any SVG stuff.
    Limitation: only B&W images are supported.
    """
    def __init__(self,
                 latent_dim: int = 128,
                 render_size: int = 128,
                 **kwargs) -> None:
        super().__init__(**kwargs)

        self.latent_dim = latent_dim
        self.render_size = render_size

        self.vector_decoder = nn.Sequential(
                nn.Linear(latent_dim, 256),
                nn.ReLU(),
                nn.Linear(256, 512),
                nn.ReLU(),
                nn.Linear(512, 1024),
                nn.ReLU(),
                nn.Linear(1024, 2048),
                nn.ReLU(),
                nn.Linear(2048, 4096),
                nn.ReLU(),
                nn.Linear(4096, 4096*2),
                nn.ReLU(),
                nn.Linear(4096*2, 1 * render_size * render_size),
                nn.Sigmoid()
            )
        
    def forward(self, z: Tensor, **kwargs) -> Tensor:
        """
        z is a single timestep of shape (bs, latent_dim)
        """
        raster_images = self.vector_decoder(z)
        raster_images = raster_images.view(-1, 1, self.render_size, self.render_size)
        raster_images = raster_images.repeat(1, 3, 1, 1)
        return [raster_images]