import torch
from torch import Tensor
from torch import nn
from torch.nn import functional as F
from typing import List
import pydiffvg


class MLPVectorHead(nn.Module):
    """
    The MLP vector head is the simplest possible head for VectorGPT. It takes the latent vector generated by the transformer and predicts the coordinates of cubic Bezier curves directly through a linear layer.
    
    Constructor Args:
        - latent_dim: int, the dimensionality of the latent vector input
        - segments: int, the number of segments that make a single path, default 4
        - render_size: int, the size of the rasterized image, default 128
        - max_stroke_width: float, the width of the stroke of the cubic Bezier curves, default 1.0
    """
    def __init__(
        self,
        latent_dim: int,
        segments: int = 4,
        render_size: int = 128,
        max_stroke_width: float = 1.0,
        filled: bool = False,
        **kwargs
    ) -> None:
        super(MLPVectorHead, self).__init__()

        self.latent_dim = latent_dim
        self.segments = segments
        self.render_size = render_size
        self.max_stroke_width = max_stroke_width
        self.filled = filled

        self.point_predictor = nn.Sequential(
            # nn.Linear(latent_dim, 256),
            # nn.SELU(),
            # nn.Linear(256, 256),
            # nn.SELU(),
            nn.Linear(
                self.latent_dim, 2 + (self.segments * 3 * 2)
            ),  # 2 for start coordinates, then 3 points per path (they're connected) with 2 coordinates per point
            nn.Sigmoid(),
        )

        self.stop_predictor = nn.Sequential(
            nn.Linear(self.latent_dim, 1),
            nn.Sigmoid(),
        )

        self.stroke_predictor = nn.Sequential(
            nn.Linear(self.latent_dim, 1),
            nn.Sigmoid(),
        )

        self.alpha_predictor = nn.Sequential(
            nn.Linear(self.latent_dim, 1),
            nn.Sigmoid(),
        )

    def raster(
        self,
        all_points: Tensor,
        stroke_widths: Tensor,
        alphas: Tensor,
        color: Tensor = Tensor([0.0, 0.0, 0.0, 1.0]),
        verbose: bool = False,
        white_background: bool = True,
        **kwargs
    ) -> Tensor:
        """
        Rasterizes the predicted points of the cubic Bezier curves.

        Args:
            all_points: Tensor of shape (batch_size, 2 + self.segments * 3, 2)
            stroke_widths: Tensor of shape (batch_size, 1)
            alphas: Tensor of shape (batch_size, 1)
            color: Tensor of shape (4)
            verbose: bool, currently unused
            white_background: bool, if True, the output will have a white background

        Returns:
            output: Tensor of shape (batch_size, 4, self.render_size, self.render_size)
        """
        device = all_points.device
        if verbose:
            render_size = 768
        else:
            render_size = self.render_size

        all_points = all_points * render_size
        #stroke_widths = stroke_widths * self.max_stroke_width  # scale the stroke width because of Sigmoid activation
        num_ctrl_pts = torch.zeros(self.segments, dtype=torch.int32).to(device) + 2
        outputs = []

        if self.filled:
            fill_color = color
        else:
            fill_color = None

        for batch_idx in range(all_points.shape[0]):
            render = pydiffvg.RenderFunction.apply
            shapes = []
            shape_groups = []
            points = all_points[batch_idx].contiguous()  # is a prediction of the model
            alpha = alphas[batch_idx]  # is a prediction of the model
            color[-1] = alpha  # is a prediction of the model
            stroke_width = stroke_widths[batch_idx]  # is a prediction of the model

            path = pydiffvg.Path(
                num_control_points=num_ctrl_pts,
                points=points,
                is_closed=False,
                # stroke_width=torch.tensor([5.]),  # this is fine
                # stroke_width=torch.tensor([5.], requires_grad=True),  # this also breaks the backpropagation
                stroke_width=stroke_width,  # this breaks the backpropagation
            )

            shapes.append(path)
            path_group = pydiffvg.ShapeGroup(
                shape_ids=torch.tensor([len(shapes) - 1]),
                fill_color=fill_color,
                stroke_color=color,
            )
            shape_groups.append(path_group)
            scene_args = pydiffvg.RenderFunction.serialize_scene(
                render_size, render_size, shapes, shape_groups
            )
            out = render(
                render_size,  # width
                render_size,  # height
                3,  # num_samples_x
                3,  # num_samples_y
                102,  # seed
                None,
                *scene_args
            )
            out = out.permute(2, 0, 1).view(4, render_size, render_size)
            outputs.append(out)
        output = torch.stack(outputs).to(all_points.device)
        if white_background:
            alpha = output[:, 3:4, :, :]
            output_white_bg = output[:, :3, :, :] * alpha + (1 - alpha)
            output = torch.cat([output_white_bg, alpha], dim=1)
        del num_ctrl_pts
        return output

    def forward(self, z: Tensor, verbose: bool = False) -> Tensor:
        point_predictions = self.point_predictor(z)
        stroke_widths = self.stroke_predictor(z)
        alphas = self.alpha_predictor(z)
        stop_predictions = self.stop_predictor(z)

        batch_size = point_predictions.shape[0]
        point_predictions = point_predictions.view(batch_size, 1 + self.segments * 3, 2)

        raster_images = self.raster(point_predictions, stroke_widths, alphas, verbose=verbose)

        return raster_images, stop_predictions
